# Generated by Django 3.1.7 on 2021-03-23 07:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_category_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
