# Generated by Django 3.1.7 on 2021-03-28 12:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20210323_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
