# Generated by Django 3.1.7 on 2021-03-28 13:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20210328_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
