# Generated by Django 3.1.7 on 2021-05-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_auto_20210522_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
