# Generated by Django 3.1.7 on 2021-05-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcart',
            old_name='days',
            new_name='distance',
        ),
    ]
