# Generated by Django 3.1.7 on 2021-05-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20210529_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='distance',
            field=models.FloatField(),
        ),
    ]
